version: '3.8'

services:
  # app:
  #   build: .
  #   container_name: go_app
  #   env_file:
  #     - .env
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     TYPESENSE_HOST: ${TYPESENSE_HOST}
  #     TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
  #     SERVER_PORT: ${SERVER_PORT}
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #     - typesense
  #   networks:
  #     - app_network
  
  # postgres:
  #   image: postgres:16
  #   container_name: postgres_db
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: ex_typesense
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app_network

  typesense:
    image: typesense/typesense:0.25.2
    container_name: typesense_search
    env_file:
      - .env
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --listen-port 8108 --enable-cors'

volumes:
  typesense_data:

