version: '3'

vars:
  APP_NAME: go-typesense-app
  DOCKER_COMPOSE_FILE: docker-compose.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  deps:
    desc: Download Go dependencies
    cmds:
      - go mod download
      - go mod tidy

  dev:
    deps: [deps]
    desc: Run the application in development mode with live reload
    cmds:
      - go run ./cmd/server/main.go

  dcd:
    desc: Stop all services
    cmds:
      - docker-compose down

  up:
    deps: [dcd]
    desc: Start all services with Docker Compose
    cmds:
      - docker-compose up --build

  dir-backup:
    desc: Create a backup of the current directory
    cmds:
      - mkdir -p ./backups

  backup-tss:
    deps: [dir-backup]
    desc: Create Typesense backup inside container and copy to host
    cmds:
      - docker exec typesense_search tar -czf /tmp/typesense_backup-$(date +%d-%m-%Y).tar.gz -C /data .
      - docker cp typesense_search:/tmp/typesense_backup-$(date +%d-%m-%Y).tar.gz ./backups/
      - docker exec typesense_search rm /tmp/typesense_backup-$(date +%d-%m-%Y).tar.gz
      - echo "Backup copied to ./backups/ directory"
      
  hub:
    desc: Build and push Docker image to Docker Hub
    cmds:
#      - docker login
      - docker build -t rafaelcarvalhocaetano/user-sense:latest .
      - docker push rafaelcarvalhocaetano/user-sense:latest

  deploy-postgres:
    desc: Apply the manifest for Typesense
    cmds:
      - kubectl apply -f ./k8s/postgres.yaml

  deploy-typesense:
    desc: Apply the manifest for Typesense
    cmds:
      - kubectl apply -f ./k8s/typesense.yaml

  deploy-user-sense:
    desc: Apply the manifest for api user-sense
    cmds:
      - kubectl apply -f ./k8s/user-sense.yaml
  
  k:
    desc: Apply all Kubernetes manifests
    deps:
#      - hub
      - deploy-postgres
      - deploy-typesense
      - deploy-user-sense

  kd:
    desc: Delete all Kubernetes resources
    cmds:
      - kubectl delete -f ./k8s/postgres.yaml
      - kubectl delete -f ./k8s/typesense.yaml
      - kubectl delete -f ./k8s/user-sense.yaml
