
## Create Template
POST http://localhost:3000/api/v1/dojo/template
Content-Type: application/json
Authorization: "Bearer EAAV2kUE4Mf8BO5YinQFIHE5ccD44wjwyCFtmYNEcjPLERKCoW9D7goy6PXmo24Tq8o9LjX2CF3vK2fv8P3oyKrmgtx7eZCa3uOAl5VSkovJZAkqtjwsKhDZAMz8C5lI6ZALBuE6cHqDAFU8WxtUZBKrTFXSXRC6i4qJNa3423z7GGQSBmo13snV4RJGCioxEdZBwsnxdktmf8uW6jFFz9Dn3CA5NRXWUpj788ZD"

{
  "name": "000xodo_data",
  "language": "pt_BR",
  "category": "marketing",
  "component": {
		"header":  {
      "type": "HEADER",
      "format": "text",
			"text": "Ola, {{1}}",
			"example": {
        "header_text": ["usuario"]
      }
    },
		"body": {
      "type": "body",
		 	"text": "Chegou a hora de resgatar seu aditivo do STP Club.\n\nVá até o seu posto, clique no link abaixo e apresente o QRCode ao frentista."
    },
		"footer": {
			"type": "footer",
			"text": "XodoIAG"
		},
    "buttons": {
      "type": "buttons",
      "buttons": [
				 {
          "type": "QUICK_REPLY",
          "text": "Gostei",
					"payload": "33333"
        },
        {
          "type":"QUICK_REPLY",
          "text": "Não Gostei",
					"payload": "123"
        }
      ]
    }
	}
}
