name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ACCOUNT: ${{ secrets.GCP_CREDENTIALS }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.1
        with:
          service_account_key: ${{ env.SERVICE_ACCOUNT }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Enable Cloud Run API
        run: gcloud services enable run.googleapis.com

      - name: Build and Deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/${PROJECT_ID}/your-service-name
          gcloud run deploy your-service-name --image gcr.io/${PROJECT_ID}/your-service-name --platform managed --region us-central1 --allow-unauthenticated
